name: radarx-dev
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python >=3.9,<3.13
  - pydata-sphinx-theme
  - myst-parser
  - sphinx
  - sphinx-copybutton
  - sphinx-favicon
  - nbsphinx
  - ipykernel
  - h5netcdf
  - h5py
  - lat_lon_parser
  - netCDF4
  - open-radar-data>=0.1.0
  - proj
  - proj-data
  - pyproj
  - xarray>=2024.10.0
  - xmltodict
  - cartopy
  - cmweather
  - dask
  - matplotlib-base
  - scipy<=1.14.1
  - boto3
  - arm_pyart
  - ffmpeg
  - zarr
  - pooch
  - xradar
  - fsspec
  - wradlib
  - arm_pyart
  - hvplot
  - bokeh
  - holoviews
  - geoviews
  - nbclassic
  - itables
  - pip
  - pip:
    - git+https://github.com/MeteoSwiss/fast-barnes-py.git
